enum ENavbar {
  PROFILE = 'PROFILE',
  CHATS = 'CHAT',
  GROUPS = 'GROUPS',
  CONTACTS = 'CONTACTS',
  SEARCH = 'SEARCH',
  INVITATION = 'INVITATION',
  SETTINGS = 'SETTINGS',
  NOTIFICATIONS = 'NOTIFICATIONS',
}

export default ENavbar;
