enum EUser {
  STATUS_ACTIVE = 'ACTIVE',
  STATUS_DEACTIVE = 'DEACTIVE',
  STATUS_INACTIVE = 'INACTIVE',
  ROLE_USER = 'USER',
  ROLE_ADMIN = 'ADMIN',
  FRIEND_STATUS_REQUESTED = 'REQUESTED',
  FRIEND_STATUS_ACCEPTED = 'ACCEPTED',
}

export default EUser;
