export enum ESocketEvent {
  CONNECT = 'connect',
  DISCONNECT = 'disconnect',
  SEND_MESSAGE = 'SEND_MESSAGE',
  GET_MESSAGE = 'GET_MESSAGE',
  SUBSCRIBE = 'SUBSCRIBE',
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  GET_FRIEND_REQUEST = 'GET_FRIEND_REQUEST',
  ONLINE = 'ONLINE',
}
