export enum ESocketEvent {
  CONNECT = 'connect',
  DISCONNECT = 'disconnect',
  SEND_MESSAGE = 'SEND_MESSAGE',
  GET_MESSAGE = 'GET_MESSAGE',
  SUBSCRIBE = 'SUBSCRIBE',
  TYPING = 'TYPING',
  STOP_TYPING = 'STOP_TYPING',
  FRIEND_REQUEST = 'FRIEND_REQUEST',
  GET_FRIEND_REQUEST = 'GET_FRIEND_REQUEST',
  ONLINE = 'ONLINE',
  CANCEL_OR_ACCEPT_FRIEND_REQUEST = 'CANCEL_OR_ACCEPT_FRIEND_REQUEST',
}
